# -*- coding: utf-8 -*-
"""List.Assignment 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1olN9JnI2mjV9uBEO1ehmU3B4SF8jSMw5
"""

#2.Write a Program to interchange first and last elements in a list
K1 = [12,35,98,52]
K1[0],K1[-1] = K1[-1],K1[0]
print(K1)

#3.Program to swap two elements in a list
K1 = [12,35,98,52]
K1[0],K1[2] = K1[2],K1[0]
print(K1)

#4.Swap elements in String list
P1 = ["Bhushit","Jain","is","king"]
P1[0],P1[3] = P1[3],P1[0]
print(P1)

#5.Ways to find length of list
O1 = [12,35,98,52,45,76,87,98]
print(len(O1))

#6.Maximum of two numbers in Python
I1 = [12,35,98,52,45,76,87,98]
print(max(I1))

#7.Minimum of two numbers in Python
U1 = [12,35,98,52,45,76,87,98]
print(min(U1))

#8.Ways to check if element exists in list
Y1 = [12,35,98,52,45,76,87,98]
if 87 in Y1:
    print("Yes")
else:
    print("No")

#9.Different ways to clear a list in Python
U2 = [12,35,98,52,45,76,87,98]
U2.clear()
print(U2)

#10.Reversing a List
O2 = [12,35,98,52,45,76,87,98]
O2.reverse()
print(O2)

#11.Cloning or Copying a list
P2 = [12,35,98,52,45,76,87,98]
P3 = P2.copy()
print(P3)

#12.Count occurrences of an element in a list
I2 = [12,35,98,52,45,76,87,98]
print(I2.count(98))

#13.Program to find sum and average of List in Python
O3 = [12,35,98,52,45,76,87,98]
print(sum(O3))
print(sum(O3)/len(O3))

#14.Sum of number digits in List
L1 = [12,35,98,52,45,76,87,98]
sum = 0
for i in L1:
    sum += i
print(sum)

#15.Multiply all numbers in the list
K2 = [12,35,98,52,45,76,87,98]
mul = 1
for i in K2:
    mul *= i
print(mul)

#16.Program to find smallest number in a list
L3 = [12,35,98,52,45,76,87,98]
print(min(L3))

#17.Program to find largest number in a list
M1 = [12,35,98,52,45,76,87,98]
print(max(M1))

#18.Program to find second largest number in a list
M2 = [12,35,98,52,45,76,87,98]
M2.sort()
print(M2[-2])

#19.Program to print even numbers in a list
E1 = [12,35,98,52,45,76,87,98]
for i in E1:
    if i%2==0:
        print(i)

#20.Program to print odd numbers in a List
O4 = [12,35,98,52,45,76,87,98]
for i in O4:
    if i%2!=0:
        print(i)

#21.Program to print all even numbers in a range
L2 = [12,35,98,52,45,76,87,98]
for i in L2:
    if i%2==0:
        print(i)

#22.Program to print all odd numbers in a range
L3 = [12,35,98,52,45,76,87,98]
for i in L3:
    if i%2!=0:
        print(i)

#23.Program to count Even and Odd numbers in a List
L4 = [12,35,98,52,45,76,87,98]
even = 0
odd = 0
for i in L4:
    if i%2==0:
        even += 1
    else:
        odd += 1
print(even)
print(odd)

#24.Program to print positive numbers in a list
L5 = [12,35,98,52,45,76,87,98]
for i in L5:
    if i>0:
        print(i)

#25.Program to print negative numbers in a list
L6 = [12,35,-98,-52,-45,76,87,98]
for i in L6:
    if i<0:
        print(i)

#26.Program to print all positive numbers in a range
L7 = [12,35,98,52,45,76,87,98]
for i in L7:
    if i>0:
        print(i)

#27.Program to count positive and negative numbers in a list
J1 = [12,35,98,52,45,76,87,98]
pos = 0
neg = 0
for i in J1:
    if i>0:
        pos += 1
    else:
        neg
        neg += 1
print(pos)
print(neg)

#28.Remove multiple elements from a list in Python
K3 = [12,35,98,52,45,76,87,98]
del K3[0]
print(K3)

#29.Remove multiple elements from a list in Python
K4 = [12,35,98,52,45,76,87,98]
del K4[0:2]
print(K4)

#30.Remove empty tuples from a list
K5 = [12,35,98,52,45,76,87,98]
K5.remove(12)
print(K5)

#31.Program to print duplicates from a list of integers
L9 = [12,35,98,52,45,76,87,98]
for i in L9:
    if L9.count(i)>1:
        print(i)

